package com.checkthelogs.musicservice;


import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import org.junit.Test;

import static java.lang.String.format;
import static junit.framework.TestCase.assertEquals;

public class MusicServiceIT {

    @Test
    public void sayHelloEndpointReturnsHelloMessage() throws UnirestException {

        //Example of how we can retrieve the app.host and app.port values generated by the docker maven plugin
        String appHost = System.getProperty("app.host");
        String appPort = System.getProperty("app.port");
        String helloEnpointUrl = format("http://%s:%s/sayHello", appHost, appPort);

        HttpResponse<String> response = Unirest.get(helloEnpointUrl).asString();

        String expectedHelloMessage = "Hello from music-service";
        assertEquals(expectedHelloMessage, response.getBody());
    }
}
